# -*- coding: utf-8 -*-
"""Alg.classificação_19/06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AuYIJD0UgR9L1QgsuoJq8xhDfVNobG2a
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# ==========================
# 1. Carregamento dos dados
# ==========================
df = pd.read_csv("AI_Impact_on_Health_Dataset_5000_Enhanced.csv")

# ==========================
# 2. Pré-processamento
# ==========================

# Remover ID
df = df.drop("Participant_ID", axis=1)

# Transformar variáveis categóricas
df = pd.get_dummies(df, drop_first=True)

# Variável alvo
y = df["Risk_Category_Low"]  # exemplo de classificação binária

# Remover alvo das features
X = df.drop("Risk_Category_Low", axis=1)

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Normalização
scaler = StandardScaler()

X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

# ==========================
# 3. Regressão Logística
# ==========================
lr = LogisticRegression(max_iter=1000)

lr.fit(X_train_sc, y_train)

pred_lr = lr.predict(X_test_sc)

# ==========================
# 4. KNN
# ==========================
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_sc, y_train)

pred_knn = knn.predict(X_test_sc)

# ==========================
# 5. Árvore de Decisão
# ==========================
tree = DecisionTreeClassifier(random_state=42)

tree.fit(X_train, y_train)

pred_tree = tree.predict(X_test)

# ==========================
# 6. Avaliação
# ==========================
acc_lr = accuracy_score(y_test, pred_lr)
acc_knn = accuracy_score(y_test, pred_knn)
acc_tree = accuracy_score(y_test, pred_tree)

print("\n===== RESULTADOS =====")
print(f"Regressão Logística: {acc_lr:.4f}")
print(f"KNN: {acc_knn:.4f}")
print(f"Árvore de Decisão: {acc_tree:.4f}")

# Comparação
resultados = {
    "Regressão Logística": acc_lr,
    "KNN": acc_knn,
    "Árvore de Decisão": acc_tree
}

melhor_modelo = max(resultados, key=resultados.get)

print("\n===== MELHOR MODELO =====")
print(f"{melhor_modelo} -> {resultados[melhor_modelo]:.4f}")

# Relatórios
print("\n===== RELATÓRIO - REGRESSÃO LOGÍSTICA =====")
print(classification_report(y_test, pred_lr))

print("\n===== RELATÓRIO - KNN =====")
print(classification_report(y_test, pred_knn))

print("\n===== RELATÓRIO - ÁRVORE DE DECISÃO =====")
print(classification_report(y_test, pred_tree))