# -*- coding: utf-8 -*-
"""Classificador_Titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLF3BmNJqWRUO8xA7QGJbiHzZk6avFVQ

# Importar Bibliotecas
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import pandas as pd

"""# Carregar Dataset Titanic"""

titanic = pd.read_csv('tested.csv')

print(titanic.head())

"""# Separar Feature(x) e label (y)"""

titanic.columns = titanic.columns.str.strip()
print(titanic.head())

titanic["Sex"]=titanic["Sex"].map({"male":0,"female":1})
titanic=pd.get_dummies(titanic,columns=["Embarked"])

titanic = titanic.drop(columns=["Ticket","Cabin","Name"])
X = titanic.drop("Survived", axis=1)
y = titanic["Survived"]

print("X:", X.shape)
print("y:", y.shape)

mediana_classificacao = X['Age'].median()
X['Age'] = X['Age'].fillna(mediana_classificacao)

min_val = X['Age'].min()
max_val = X['Age'].max()

X['age_normalizada'] = (X['Age'] - min_val) / (max_val - min_val)
print("Normalização:\n", X['age_normalizada'])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(titanic.info())

from sklearn.tree import DecisionTreeClassifier

modelo = DecisionTreeClassifier(max_depth=3, random_state=4)

modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

from sklearn.metrics import accuracy_score

acuracia = accuracy_score(y_test, y_pred)

print(f"Acurácia: {acuracia:.2f}")
print(f"Acurácia em porcentagem: {acuracia * 100:.2f}%")