# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Carregar os dados
dados = pd.read_csv("obeso.csv")

dados["Gender"]=dados["Gender"].map({"Male":0,"Female":1})
# Se no CSV original os dados são texto e você quer transformar em números:
mapeamento_labels = {
    "Underweight": 0,
    "Overweight": 1,
    "Obese": 2,
    "Normal Weight": 3
}
dados["Label"] = dados["Label"].map(mapeamento_labels)
print(dados["Label"])

X = dados.drop("Label", axis=1)
y = dados["Label"]



# 2. Dividir em treino e teste
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. Padronizar os dados
scaler = StandardScaler()
X_treino_escalado = scaler.fit_transform(X_treino)
X_teste_escalado = scaler.transform(X_teste)

# 4. Criar e treinar o modelo
modelo = LogisticRegression()
modelo.fit(X_treino_escalado, y_treino)

# 5. Fazer previsões
y_pred = modelo.predict(X_teste_escalado)

# 6. Avaliar o modelo
print("Acurácia:", accuracy_score(y_teste, y_pred))
print("Matriz de confusão:")
print(confusion_matrix(y_teste, y_pred))
print("Relatório de classificação:")
print(classification_report(y_teste, y_pred))

# ========================================================
# 7. GERAR O GRÁFICO DA MATRIZ DE CONFUSÃO
# ========================================================

# Criamos a matriz numérica básica
cm = confusion_matrix(y_teste, y_pred)

# Pegamos os nomes das classes diretamente na ordem correta (0, 1, 2, 3)
# sorted(mapeamento_labels, key=mapeamento_labels.get) ordena as palavras pelos números delas
nomes_classes = sorted(mapeamento_labels, key=mapeamento_labels.get)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm, display_labels=nomes_classes
)

# Plota o gráfico usando um mapa de cores bonito (Blues)
disp.plot(cmap=plt.cm.Blues, values_format="d")

# Ajustes finais do Matplotlib
plt.title("Matriz de Confusão - Classificação de Peso")
plt.xticks(rotation=45)
plt.tight_layout()

# Exibe o gráfico na tela
plt.show()